CREATE DATABASE IF NOT EXISTS aubede CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aubede;

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    category VARCHAR(80) NOT NULL,
    price DECIMAL(12,2) NOT NULL DEFAULT 0,
    old_price DECIMAL(12,2) NULL,
    image VARCHAR(500) NULL,
    rating DECIMAL(2,1) NOT NULL DEFAULT 5.0,
    reviews INT UNSIGNED NOT NULL DEFAULT 0,
    description TEXT NOT NULL,
    tag VARCHAR(50) NULL,
    stock INT UNSIGNED NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX(category),
    INDEX(active)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(160) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    location VARCHAR(180) NOT NULL,
    address TEXT NULL,
    payment_method VARCHAR(50) NOT NULL,
    total DECIMAL(12,2) NOT NULL DEFAULT 0,
    status ENUM('Nouvelle','En préparation','Expédiée','Livrée','Annulée') NOT NULL DEFAULT 'Nouvelle',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX(status),
    INDEX(created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NULL,
    product_name VARCHAR(180) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(12,2) NOT NULL,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL
) ENGINE=InnoDB;
